# python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "retr_attn"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"top_k": 1024}'

# python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "retr_attn"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"top_k": 2048}'

# python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 1024, "ensure_first_chunk": true}'

# python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 2048, "ensure_first_chunk": true}'

# python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 4096, "ensure_first_chunk": true}'


python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 1024, "ensure_first_chunk": true, "scaling_factor": 1.05}'

python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 2048, "ensure_first_chunk": true, "scaling_factor": 1.05}'

python run_scbench.py     --task scbench_kv     --model_name_or_path meta-llama/Llama-3.1-8B-Instruct     --data_dir ./data     --output_dir ./results     --attn_type "dense"     --kv_type "quest"     --use_chat_template     --trust_remote_code     --max_seq_length 64000     --tensor_parallel_size 1     --num_eval_examples 50  --hyper_param '{"token_budget": 4096, "ensure_first_chunk": true, "scaling_factor": 1.05}'